# Generated by Django 5.0.14 on 2026-07-17 11:08

from django.db import migrations
from django.contrib.auth.hashers import make_password
import uuid

def seed_data(apps, schema_editor):
    Organization = apps.get_model('core', 'Organization')
    User = apps.get_model('core', 'User')
    OrganizationMember = apps.get_model('core', 'OrganizationMember')

    # Ensure we don't duplicate if it already runs
    if not User.objects.filter(email='admin@example.com').exists():
        org = Organization.objects.create(name='Acme Corp')
        
        user = User.objects.create(
            email='admin@example.com',
            password=make_password('password123'),
            is_staff=True,
            is_superuser=True,
            is_active=True,
            current_organization=org
        )

        OrganizationMember.objects.create(
            user=user, 
            organization=org, 
            role='ADMIN'
        )

        # ---------------------------------------------
        # Seed Sample Data for the Kanban Board
        # ---------------------------------------------
        Project = apps.get_model('projects', 'Project')
        Task = apps.get_model('projects', 'Task')

        # Create a Project
        project = Project.objects.create(
            organization=org,
            name='Alpha Launch',
            description='Launch the initial version of OrgFlow'
        )

        # Create Tasks
        Task.objects.create(
            organization=org,
            project=project,
            title='Design system overhaul',
            description='Implement glassmorphism and dark mode',
            status='DONE',
            reporter=user,
            assignee=user
        )

        Task.objects.create(
            organization=org,
            project=project,
            title='Configure PostgreSQL on Render',
            description='Migrate from SQLite to PostgreSQL for production',
            status='IN_PROGRESS',
            reporter=user,
            assignee=user
        )

        Task.objects.create(
            organization=org,
            project=project,
            title='Implement drag-and-drop on Kanban',
            description='Add react-beautiful-dnd for task columns',
            status='TODO',
            reporter=user,
            assignee=user
        )

        Task.objects.create(
            organization=org,
            project=project,
            title='Add unit tests for Tenant Isolation',
            description='Prove Org A cannot see Org B data',
            status='DONE',
            reporter=user,
            assignee=user
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
