# Generated by Django 5.0.14 on 2026-07-17 11:08

from django.db import migrations
from django.contrib.auth.hashers import make_password
import uuid

def seed_data(apps, schema_editor):
    Organization = apps.get_model('core', 'Organization')
    User = apps.get_model('core', 'User')
    OrganizationMember = apps.get_model('core', 'OrganizationMember')

    # Ensure we don't duplicate if it already runs
    if not User.objects.filter(email='admin@example.com').exists():
        org = Organization.objects.create(name='Acme Corp')
        
        user = User.objects.create(
            email='admin@example.com',
            password=make_password('password123'),
            first_name='Aadiy',
            last_name='Khan',
            is_staff=True,
            is_superuser=True,
            is_active=True,
            current_organization=org
        )

        OrganizationMember.objects.create(
            user=user, 
            organization=org, 
            role='ADMIN'
        )

        Project = apps.get_model('projects', 'Project')
        Task = apps.get_model('projects', 'Task')

        project = Project.objects.create(
            organization=org,
            name='Alpha Launch',
            description='Ship the initial version of OrgFlow to production'
        )

        # TODO tasks
        for title in [
            'Set up CI/CD pipeline with GitHub Actions',
            'Write API documentation for public endpoints',
            'Implement role-based access control for viewers',
        ]:
            Task.objects.create(organization=org, project=project, title=title, status='TODO', reporter=user, assignee=user)

        # IN_PROGRESS tasks
        for title in [
            'Configure PostgreSQL on production',
            'Build notification service for task updates',
        ]:
            Task.objects.create(organization=org, project=project, title=title, status='IN_PROGRESS', reporter=user, assignee=user)

        # DONE tasks
        for title in [
            'Design system and component library',
            'Implement JWT authentication flow',
            'Add tenant isolation at the queryset level',
            'Deploy backend to Render',
        ]:
            Task.objects.create(organization=org, project=project, title=title, status='DONE', reporter=user, assignee=user)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
