# Generated by Django 5.0.14 on 2026-07-17 11:08

from django.db import migrations
from django.contrib.auth.hashers import make_password
import uuid

def seed_data(apps, schema_editor):
    Organization = apps.get_model('core', 'Organization')
    User = apps.get_model('core', 'User')
    OrganizationMember = apps.get_model('core', 'OrganizationMember')

    # Ensure we don't duplicate if it already runs
    if not User.objects.filter(email='admin@example.com').exists():
        org = Organization.objects.create(name='Acme Corp')
        
        user = User.objects.create(
            email='admin@example.com',
            password=make_password('password123'),
            is_staff=True,
            is_superuser=True,
            is_active=True,
            current_organization=org
        )

        OrganizationMember.objects.create(
            user=user, 
            organization=org, 
            role='ADMIN'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
